from turtle import *
from random import randint
speed(0)

def winter():
    # Background 
    color('#d6f5fa')
    goto(-250, -250)
    begin_fill()
    for i in range(2):
        forward(500)
        left(90)
        forward(500)
        left(90)
    end_fill()
    penup()
    

    # Apartment
    goto(-250, -170)
    color('#efa200')
    pendown()
    begin_fill()
    for i in range(2):
        forward(162)
        left(90)
        forward(300)
        left(90)
    end_fill()
    penup()
    #outline
    goto(-250, 130)
    pendown()
    pensize(20)
    color('#fcfcfc')
    forward(162)
    right(90)
    forward(300)
    penup()
    #WINDOW
    pensize(1)
    color('#00baff')
    goto(-230, 80)
    pendown()
    begin_fill()
    for i in range(4):
        forward(40)
        left(90)
    end_fill()
    penup()
    goto(-170, 80)
    pendown()
    color('#f9ce06')
    begin_fill()
    for i in range(4):
        forward(40)
        left(90)
    end_fill()
    penup()
    color('#00baff')
    goto(-230, 20)
    pendown()
    begin_fill()
    for i in range(4):
        forward(40)
        left(90)
    end_fill()
    penup()
    goto(-170, 20)
    pendown()
    color('#00baff')
    begin_fill()
    for i in range(4):
        forward(40)
        left(90)
    end_fill()
    penup()
    color('#00baff')
    goto(-230, -40)
    pendown()
    begin_fill()
    for i in range(4):
        forward(40)
        left(90)
    end_fill()
    penup()
    goto(-170, -40)
    pendown()
    color('#f9ce06')
    begin_fill()
    for i in range(4):
        forward(40)
        left(90)
    end_fill()
    penup()

    # door
    goto(-200, -100)
    pendown()
    color('#c5c5c5')
    begin_fill()
    for i in range(2):
        forward(70)
        left(90)
        forward(40)
        left(90)
    end_fill()
    penup()

    #2 Apartment
    goto(-50, 80)
    color('#efa200')
    pendown()
    begin_fill()
    for i in range(2):
        forward(250)
        left(90)
        forward(162)
        left(90)
    end_fill()
    penup()
    #outline 
    color('#fcfcfc')
    goto(-55, 90)
    pensize(20)
    pendown()
    left(90)
    forward(162)
    right(90)
    forward(125)
    right(90)
    forward(162)
    left(90)
    forward(130)
    left(90)
    forward(162)
    penup()
        #WINDOW
    pensize(1)
    color('#00baff')
    goto(-30, 10)
    pendown()
    begin_fill()
    for i in range(4):
        forward(40)
        left(90)
    end_fill()
    penup()

    color('#f9ce06')
    goto(30, 10)
    pendown()
    begin_fill()
    for i in range(4):
        forward(40)
        left(90)
    end_fill()
    penup()

    color('#00baff')
    goto(-30, -120)
    pendown()
    begin_fill()
    for i in range(4):
        forward(40)
        left(90)
    end_fill()
    penup()
    # door
    goto(40, -155)
    pendown()
    color('#c5c5c5')
    begin_fill()
    for i in range(2):
        forward(40)
        left(90)
        forward(70)
        left(90)
    end_fill()
    penup()

    #tree
    goto(160, -170)
    pendown()
    color('#c14400')
    begin_fill()
    for i in range(2):
        forward(40)
        left(90)
        forward(70)
        left(90)
    end_fill()
    penup()


    goto(135, -100)
    color('#d5fcff')
    pendown()
    begin_fill()
    forward(100)
    left(125)
    forward(100)
    left(110)
    forward(100)
    left(125)
    end_fill()
    goto(135, -60)
    color('#d5fcff')
    pendown()
    begin_fill()
    forward(100)
    left(125)
    forward(100)
    left(110)
    forward(100)
    left(125)
    end_fill()
    goto(135, -20)
    color('#d5fcff')
    pendown()
    begin_fill()
    forward(100)
    left(125)
    forward(100)
    left(110)
    forward(100)
    left(125)
    end_fill()
    penup()
    goto(180, 140)
    pendown()
    begin_fill()
    color('#d5fcff')
    circle(50)
    end_fill()
    penup()
#snow

    for i in range(100):
        xwinter = randint(-250, 250)
        ywinter = randint(-170, 250)
        goto(xwinter, ywinter)
        begin_fill()
        pendown()
        color('#fcfcfc')
        circle(2)
        penup()
        end_fill()

    # Ground
    goto(-250, -250)
    color('#ebfcff')
    pendown()
    begin_fill()
    for i in range(2):
        forward(500)
        left(90)
        forward(80)
        left(90)
    end_fill()
    penup()


def autumn():
    # Background 
    color('#ffb454')
    goto(-250, -250)
    begin_fill()
    for i in range(2):
        forward(500)
        left(90)
        forward(500)
        left(90)
    end_fill()
    penup()
    # Apartment
    goto(-250, -170)
    color('#fcfcfc')
    pendown()
    begin_fill()
    for i in range(2):
        forward(162)
        left(90)
        forward(300)
        left(90)
    end_fill()
    penup()
    #outline
    goto(-250, 130)
    pendown()
    pensize(20)
    color('#efa200')
    forward(162)
    right(90)
    forward(150)
    right(90)
    forward(162)
    goto(-88,-20)
    left(90)
    forward(150)
    right(90)
    forward(162)
    left(180)
    penup()
    #WINDOW
    pensize(1)
    color('#00baff')
    goto(-240, 30)
    pendown()
    begin_fill()
    for i in range(4):
        forward(50)
        left(90)
    end_fill()
    penup()
    goto(-170, 30)
    pendown()
    begin_fill()
    for i in range(4):
        forward(50)
        left(90)
    end_fill()
    penup()
    color('#00baff')
    goto(-230, 20)
    pendown()
    color('#00baff')
    penup()
    goto(-240, -120)
    pendown()
    begin_fill()
    for i in range(4):
        forward(50)
        left(90)
    end_fill()
    penup()
    # door
    goto(-160, -160)
    pendown()
    color('#c5c5c5')
    begin_fill()
    for i in range(2):
        forward(40)
        left(90)
        forward(70)
        left(90)
    end_fill()
    penup()
#2 Apartment
    goto(-50, -170)
    color('#fcfcfc')
    pendown()
    begin_fill()
    for i in range(2):
        forward(162)
        left(90)
        forward(250)
        left(90)
    end_fill()
    penup()
#outline
    pensize(20)
    color('#efa200')
    goto(-50, 80)
    pendown()
    forward(162)
    goto(-50, 80)
    right(90)
    forward(250)
    penup()
#window
    pensize(1)
    color('#00baff')
    goto(-25, 30)
    pendown()
    begin_fill()
    for i in range(4):
        forward(50)
        left(90)
    end_fill()
    penup()
    color('#f9ce06')
    goto(40, 30)
    pendown()
    begin_fill()
    for i in range(4):
        forward(50)
        left(90)
    end_fill()
    penup()
    color('#00baff')
    goto(-25, -90)
    pendown()
    begin_fill()
    for i in range(4):
        forward(50)
        left(90)
    end_fill()
    penup()
    # door
    goto(50, -100)
    pendown()
    color('#c5c5c5')
    begin_fill()
    for i in range(2):
        forward(70)
        left(90)
        forward(40)
        left(90)
    end_fill()
    penup()
    left(90)
    #tree
    goto(160, -170)
    pendown()
    color('#c14400')
    begin_fill()
    for i in range(2):
        forward(40)
        left(90)
        forward(70)
        left(90)
    end_fill()
    penup()
    goto(135, -100)
    color('#ff8800')
    pendown()
    begin_fill()
    forward(100)
    left(125)
    forward(100)
    left(110)
    forward(100)
    left(125)
    end_fill()
    penup()
    goto(135, -60)
    pendown()
    begin_fill()
    forward(100)
    left(125)
    forward(100)
    left(110)
    forward(100)
    left(125)
    end_fill()
    penup()
    goto(135, -20)
    pendown()
    begin_fill()
    forward(100)
    left(125)
    forward(100)
    left(110)
    forward(100)
    left(125)
    end_fill()
    penup()
    goto(180, 140)
    pendown()
    begin_fill()
    color('#ffd800')
    circle(50)
    end_fill()
    penup()
    # Ground
    goto(-250, -250)
    color('#ff8800')
    pendown()
    begin_fill()
    for i in range(2):
        forward(500)
        left(90)
        forward(80)
        left(90)
    end_fill()
    penup() 
def spring():
    # Background 
    color('#ff94d6')
    goto(-250, -250)
    begin_fill()
    for i in range(2):
        forward(500)
        left(90)
        forward(500)
        left(90)
    end_fill()
    penup()
    #aparment
    goto(-250, -170)
    color('#efa200')
    pendown()
    begin_fill()
    for i in range(2):
        forward(162)
        left(90)
        forward(300)
        left(90)
    end_fill()
    penup()
    #outline
    goto(-250, 130)
    pendown()
    pensize(20)
    color('#fcfcfc')
    forward(162)
    penup()
    left(270)
#WINDOW
    pensize(1)
    color('#00baff')
    goto(-230, 80)
    pendown()
    begin_fill()
    for i in range(4):
        forward(40)
        left(90)
    end_fill()
    penup()
    goto(-170, 80)
    pendown()
    color('#f9ce06')
    begin_fill()
    for i in range(4):
        forward(40)
        left(90)
    end_fill()
    penup()
    color('#00baff')
    goto(-230, 20)
    pendown()
    begin_fill()
    for i in range(4):
        forward(40)
        left(90)
    end_fill()
    penup()
    goto(-170, 20)
    pendown()
    color('#00baff')
    begin_fill()
    for i in range(4):
        forward(40)
        left(90)
    end_fill()
    penup()
    color('#00baff')
    goto(-230, -40)
    pendown()
    begin_fill()
    for i in range(4):
        forward(40)
        left(90)
    end_fill()
    penup()
    goto(-170, -40)
    pendown()
    color('#f9ce06')
    begin_fill()
    for i in range(4):
        forward(40)
        left(90)
    end_fill()
    penup()

    # door
    goto(-200, -100)
    pendown()
    color('#c5c5c5')
    begin_fill()
    for i in range(2):
        forward(70)
        left(90)
        forward(40)
        left(90)
    end_fill()
    penup()
    left(90)
    #tree
    goto(-30, -170)
    pendown()
    color('#c14400')
    begin_fill()
    for i in range(2):
        forward(40)
        left(90)
        forward(70)
        left(90)
    end_fill()
    penup()

#tree
    goto(-55, -100)
    color('#ffd6ef')
    pendown()
    begin_fill()
    forward(100)
    left(125)
    forward(100)
    left(110)
    forward(100)
    left(125)
    end_fill()
    penup()
    goto(-55, -60)
    pendown()
    begin_fill()
    forward(100)
    left(125)
    forward(100)
    left(110)
    forward(100)
    left(125)
    end_fill()
    penup()
    goto(-55, -20)
    pendown()
    begin_fill()
    forward(100)
    left(125)
    forward(100)
    left(110)
    forward(100)
    left(125)
    end_fill()
    penup()
    #apartment2
    goto(70, -170)
    color('#fcfcfc')
    pendown()
    begin_fill()
    for i in range(2):
        forward(162)
        left(90)
        forward(300)
        left(90)
    end_fill()
    penup()
        #outline
    goto(70, 130)
    pendown()
    pensize(20)
    color('#efa200')
    forward(162)
    right(90)
    forward(150)
    right(90)
    forward(162)
    left(90)
    forward(150)
    penup()
    #WINDOW
    pensize(1)
    color('#00baff')
    goto(85, 80)
    pendown()
    begin_fill()
    for i in range(4):
        forward(50)
        left(90)
    end_fill()
    penup()
    goto(155, 80)
    pendown()
    color('#f9ce06')
    begin_fill()
    for i in range(4):
        forward(50)
        left(90)
    end_fill()
    penup()
    goto(155, -50)
    pendown()
    color('#f9ce06')
    begin_fill()
    for i in range(4):
        forward(50)
        left(90)
    end_fill()
    penup()
        # door
    goto(95, -100)
    pendown()
    color('#c5c5c5')
    begin_fill()
    for i in range(2):
        forward(70)
        left(90)
        forward(40)
        left(90)
    end_fill()
    penup()
    left(90)
            # Ground
    goto(-250, -250)
    color('#ffd6ef')
    pendown()
    begin_fill()
    for i in range(2):
        forward(500)
        left(90)
        forward(80)
        left(90)
    end_fill()
    penup() 
    #wind
    color('#ffb7e3')
    left(30)
    pensize(5)
    for i in range(5):
        xspring = randint(-250,250)
        yspring = randint(-170, 230)
        goto(xspring, yspring)
        pendown()
        for i in range(5):
            forward(10)
            right(10)
        for i in range(5):
            forward(10)
            left(10)
        penup()
    #sun
    goto(180, 150)
    pendown()
    begin_fill()
    color('#ffb7e3')
    circle(45)
    end_fill()
    penup()
def summer():
        # Background 
    color('#00d7ff')
    goto(-250, -250)
    begin_fill()
    for i in range(2):
        forward(500)
        left(90)
        forward(500)
        left(90)
    end_fill()
    penup()
        # Apartment
    goto(-250, -170)
    color('#fcfcfc')
    pendown()
    begin_fill()
    for i in range(2):
        forward(162)
        left(90)
        forward(300)
        left(90)
    end_fill()
    penup()
    #outline
    goto(-250, 130)
    pendown()
    pensize(20)
    color('#efa200')
    forward(162)
    penup()
    goto(-250,-15)
    pendown()
    forward(162)
    right(90)
    forward(150)
    right(90)
    forward(162)
    left(180)
    penup()
        #WINDOW
    pensize(1)
    color('#00baff')
    goto(-240, 30)
    pendown()
    begin_fill()
    for i in range(4):
        forward(50)
        left(90)
    end_fill()
    penup()
    goto(-170, 30)
    pendown()
    begin_fill()
    for i in range(4):
        forward(50)
        left(90)
    end_fill()
    penup()
    pensize(10)
    goto(-240, 30)
    color('#efa200')
    pendown()
    begin_fill()
    forward(50)
    end_fill()
    penup()
    #window
    goto(-170, 30)
    color('#efa200')
    pendown()
    begin_fill()
    forward(50)
    end_fill()
    penup()
    pensize(1)
    color('#00baff')
    goto(-240, -120)
    pendown()
    begin_fill()
    for i in range(4):
        forward(50)
        left(90)
    end_fill()
    penup()
        # door
    goto(-160, -155)
    pendown()
    color('#c5c5c5')
    begin_fill()
    for i in range(2):
        forward(40)
        left(90)
        forward(70)
        left(90)
    end_fill()
    penup()
#tree
    goto(-30, -170)
    pendown()
    color('#c14400')
    begin_fill()
    for i in range(2):
        forward(40)
        left(90)
        forward(70)
        left(90)
    end_fill()
    penup()

    goto(-55, -100)
    color('#20df26')
    pendown()
    begin_fill()
    forward(100)
    left(125)
    forward(100)
    left(110)
    forward(100)
    left(125)
    end_fill()
    penup()
    goto(-55, -60)
    pendown()
    begin_fill()
    forward(100)
    left(125)
    forward(100)
    left(110)
    forward(100)
    left(125)
    end_fill()
    penup()
    goto(-55, -20)
    pendown()
    begin_fill()
    forward(100)
    left(125)
    forward(100)
    left(110)
    forward(100)
    end_fill()
    penup() 
    left(125)  
    #2 Apartment
    goto(80, -170)
    color('#fcfcfc')
    pendown()
    begin_fill()
    for i in range(2):
        forward(162)
        left(90)
        forward(300)
        left(90)
    end_fill()
    penup()
    #outline
    goto(80, 130)
    pendown()
    pensize(20)
    color('#efa200')
    forward(162)
    penup()   
    goto(80, -20)
    pendown()
    pensize(20)
    color('#efa200')
    forward(162)
    penup() 
    goto(80, -170)
    pendown()
    pensize(20)
    color('#efa200')
    forward(162)
    penup() 
        #WINDOW
    pensize(1)
    color('#00baff')
    goto(100, 30)
    pendown()
    begin_fill()
    for i in range(4):
        forward(50)
        left(90)
    end_fill()
    penup()
    goto(170, 30)
    pendown()
    begin_fill()
    for i in range(4):
        forward(50)
        left(90)
    end_fill()
    penup()
    goto(170, -120)
    pendown()
    begin_fill()
    for i in range(4):
        forward(50)
        left(90)
    end_fill()
    penup()
        # door
    goto(105, -160)
    pendown()
    color('#c5c5c5')
    begin_fill()
    for i in range(2):
        forward(40)
        left(90)
        forward(70)
        left(90)
    end_fill()
    penup()
    left(90)    
    #sun
    xsummer = randint(-150,200)
    goto(xsummer, 200)
    pendown()
    color('#ffd100')
    begin_fill()
    circle(45)
    end_fill()
    penup()
    left(90)
    #bird
    pensize(3)
    color('#000000')
    pendown()
    for i in range(5):
        forward(5)
        left(15)
    right(90)
    for i in range(5):
        forward(5)
        left(15)
    penup()
    right(90)
    forward(10)
    left(90)
    forward(10)
    right(90)
    pendown()
    for i in range(5):
        forward(5)
        left(15)
    right(90)
    for i in range(5):
        forward(5)
        left(15)
    penup()
    right(210)
    # Ground
    goto(-250, -250)
    color('#20df26')
    pendown()
    begin_fill()
    for i in range(2):
        forward(500)
        left(90)
        forward(80)
        left(90)
    end_fill()
    penup() 
